spring:
  datasource:
    url: jdbc:mysql://gamel-mysql-container:3306/gamel?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true

  data:
    redis:
      host: gamel-redis-container
      port: 6379

dynamodb:
  endpoint: http://gamel-dynamodb:8000
  region: ap-northeast-2
  accessKey: dummy
  secretKey: dummy